# Creates a Pod that can hold single or multiple containers.
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
    - image: zak22/node-webapp:1.1.1
      name: nodewebapp
      ports:
        - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
